---
title: "Simple OSPAR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Simple OSPAR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



This is a simple example of using the `harsat` with OSPAR.


```r
library(harsat)
```

# Read data from ICES extraction

There are three input data sets: 
- the contaminant data
- the station dictionary
- the quality assurance data (more accurately called a chemical methods file); 
note that this will disappear before the first release of the harsat package

Load the R package `here`, because we use the working directory to find
the data files. If you use your own data files, you will need to point to
a directory containing a copy.


```r
library(here)
working.directory <- here()
```



```r
biota_data <- ctsm_read_data(
  compartment = "biota", 
  purpose = "OSPAR",                               
  contaminants = "test_data.csv", 
  stations = "station_dictionary.csv", 
  QA = "quality_assurance.csv",
  data_path = file.path(working.directory, "data", "example_simple_OSPAR"),
  info_files = list(
    determinand = "determinand_simple_OSPAR.csv", 
    thresholds = "thresholds_biota_simple_OSPAR.csv"
  ),
  info_path = file.path(working.directory, "information"), 
  extraction = "2022/01/11",
  max_year = 2020L  
)
#> Reading station dictionary from:
#>  '/Users/stuart/git/HARSAT/data/example_simple_OSPAR/station_dictionary.csv'
#> 
#> Reading contaminant and biological effects data from:
#>  '/Users/stuart/git/HARSAT/data/example_simple_OSPAR/test_data.csv'
#> 
#> Reading QA data from '/Users/stuart/git/HARSAT/data/example_simple_OSPAR/quality_assurance.csv'
```

## Prepare data for next stage

Gets correct variable and streamlines some of the data files


```r
biota_data <- ctsm_tidy_data(biota_data)
#> 
#> Oddities will be written to 'oddities/biota' with previous oddities backed up to
#>  'oddities/biota_backup'
#> 
#> Cleaning station dictionary
#>    Duplicate stations - first one selected: see duplicate_stations.csv
#> 
#> Cleaning contaminant and biological effects data
#>    Submitted.station unrecognised by dictionary: see stations_unrecognised.csv
#>    Dropping data with no stations
```

## Construct timeseries

Identifies groups of data that form a coherent timeseries.
Also does a lot of data cleaning and processing (creates oddities folder).


```r
biota_timeSeries <- ctsm_create_timeSeries(
  biota_data,
  determinands = c("CD", "CB153", "HBCD","HBCDA", "HBCDG", "PYR1OH"), 
  determinands.control = list(
    HBCD = list(det = c("HBCDA", "HBCDB", "HBCDG"), action = "sum"),
    "LIPIDWT%" = list(det = c("EXLIP%", "FATWT%"), action = "bespoke")
  ), 
  get_basis = get_basis_biota_OSPAR
)
#> 
#> Oddities will be written to 'oddities/biota' with previous oddities backed up to
#>  'oddities/biota_backup'
#> 
#> Cleaning data
#>    Dropping stations with no data between 2015 and 2020 
#>    Dropping samples with only auxiliary variables
#>    Unexpected or missing values for 'matrix': see matrix_queries.csv
#>    Unexpected or missing values for 'basis': see basis_queries.csv
#>    Bile metabolite units changed from 'ng/g' to 'ng/ml' and from 'ug/kg' to 'ug/l'
#>    Replicate measurements, only first retained: see replicate_measurements.csv
#>    Limit of quantification less than limit of detection: see limits_inconsistent.csv
#>    Detection limit higher than data: see detection_limit_high.csv
#>    Data submitted as HBCDA, HBCDB, HBCDG summed to give HBCD
#>    Data submitted as EXLIP% or FATWT% relabelled as LIPIDWT% 
#> 
#> Creating time series data
#>    Converting data to appropriate basis for statistical analysis
#>    Losing 32 out of 392 records in basis conversion due to missing, censored
#>    or zero drywt or lipidwt values.
#>    Dropping bivalve and gastropod contaminant data collected during the
#>     spawning season, which is taken to be the following months:
#>     April, May, June, July 
#>    Dropping groups of compounds / stations with no data between 2015 and 2020
```

Identical (apart from call) to: 


```r
ctsm_create_timeSeries(
  biota_data,
  determinands = ctsm_get_determinands("biota"),
  determinands.control = list(
    HBCD = list(det = c("HBCDA", "HBCDB", "HBCDG"), action = "sum"),
    "LIPIDWT%" = list(det = c("EXLIP%", "FATWT%"), action = "bespoke")
  )
)

ctsm_create_timeSeries(
  biota_data,
  determinands.control = list(
    HBCD = list(det = c("HBCDA", "HBCDB", "HBCDG"), action = "sum"),
    "LIPIDWT%" = list(det = c("EXLIP%", "FATWT%"), action = "bespoke")
  )
)
```

# Assessment

Do the statistical analysis


```r
biota_assessment <- ctsm_assessment(
  biota_timeSeries, 
  AC = c("BAC", "EAC", "EQS", "HQS")
)
#> 
#> assessing series:  station_code 11461; determinand CB153; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 11461; determinand CD; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 12156; determinand CD; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 12164; determinand CB153; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 12164; determinand CD; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1235; determinand CB153; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1235; determinand CD; species Crassostrea gigas; matrix SB; basis D; unit ug/kg
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> 
#> assessing series:  station_code 1235; determinand HBCD; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1235; determinand HBCDA; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1235; determinand HBCDG; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 13059; determinand CB153; species Spisula solida; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 13059; determinand CD; species Spisula solida; matrix SB; basis D; unit ug/kg
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> 
#> assessing series:  station_code 1345; determinand CB153; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1345; determinand CD; species Crassostrea gigas; matrix SB; basis D; unit ug/kg
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> 
#> assessing series:  station_code 1345; determinand HBCD; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1345; determinand HBCDA; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1345; determinand HBCDG; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1381; determinand CB153; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1381; determinand CD; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1381; determinand HBCD; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1381; determinand HBCDA; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1381; determinand HBCDG; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1388; determinand CB153; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 1388; determinand CD; species Crassostrea gigas; matrix SB; basis D; unit ug/kg
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> 
#> assessing series:  station_code 2717; determinand PYR1OH; species Limanda limanda; matrix BI; method_analysis HPLC-FD; unit ng/ml 
#> 
#> assessing series:  station_code 3282; determinand CB153; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 3282; determinand CD; species Crassostrea gigas; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 3433; determinand CB153; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 3433; determinand CD; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 3441; determinand CB153; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 3441; determinand CD; species Mytilus edulis; matrix SB; basis D; unit ug/kg
#> boundary (singular) fit: see help('isSingular')
#> boundary (singular) fit: see help('isSingular')
#> 
#> assessing series:  station_code 7132; determinand CB153; species Mytilus edulis; matrix SB; basis D; unit ug/kg 
#> 
#> assessing series:  station_code 7132; determinand CD; species Mytilus edulis; matrix SB; basis D; unit ug/kg
```

Check convergence - no errors this time


```r
ctsm_check_convergence(biota_assessment$assessment)
#> character(0)
```

# Summary files


```r
summary.dir <- file.path(working.directory, "output", "example_simple_OSPAR")

if (!dir.exists(summary.dir)) {
  dir.create(summary.dir, recursive = TRUE)
}

webGroups <- list(
  levels = c("Metals", "Metabolites", "Organobromines", "Chlorobiphenyls"),  
  labels = c(
    "Metals", "PAH metabolites", "Organobromines",  "Polychlorinated biphenyls"
  )
)

classColour <- list(
  below = c(
    "BAC" = "blue", 
    "EAC" = "green", 
    "EQS" = "green",
    "HQS" = "green"
  ),
  above = c(
    "BAC" = "orange", 
    "EAC" = "red", 
    "EQS" = "red",
    "HQS" = "red"
  ), 
  none = "black"
)

ctsm_summary_table(
  biota_assessment, 
  determinandGroups = webGroups,
  classColour = classColour,
  collapse_AC = list(EAC = c("EAC", "EQS")),
  output_dir = summary.dir, 
)
```
